// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomStuffGeneratorPrivate.DatabaseClasses;

namespace RandomStuffGeneratorPrivate.Migrations
{
    [DbContext(typeof(QuoteCMSContext))]
    [Migration("20201229073830_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("RandomStuffGeneratorPrivate.DatabaseClasses.QuoteHistoryModel", b =>
                {
                    b.Property<int>("QuoteHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuoteIdentifierString")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteLifStageDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuoteLifeStageIncrement")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuoteHistoryId");

                    b.ToTable("QuoteHistoryModels");
                });

            modelBuilder.Entity("RandomStuffGeneratorPrivate.DatabaseClasses.QuoteModel", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuoteAuthor")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteIdentifierString")
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteId");

                    b.ToTable("QuoteModels");
                });
#pragma warning restore 612, 618
        }
    }
}
